name: Super-runner

on: push

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 24f2004435@ds.study.iitm.ac.in
        run: echo "me running"

    
    
